### ISSUE TITLE
지원자의 학과도 나오게 해주세요!

### ISSUE THREAD

**Issue by CaesiumY** [lee-sj/7th_apply#1]
지원자의 학과도 뽑을 수 있게 해주세요ㅎㅎ!!

**Comment by CaesiumY** [comment]
`user_major = user_page.search("#likelion_num  div:nth-child(2) > div:nth-child(1)").text
puts name[i] + ' ' + user_info.to_s.split(" ")[0] + ' ' + user_info.to_s.split(" ")[2] + ' ' + user_major.to_s.split(" ")[2]`

그냥 제가 만들었습니다ㅎㅎ 마지막 2줄만 바꿔주세용

**Comment by lee-sj** [comment]
아 바꿨는데 다른 방법이네요 ㅎㅎ 작업하던 중이었습니다. !!!
